### PR TITLE
Update README.md for 23.08

### PR DESCRIPTION
**Pull request by runiq**
The README was still referring to 22.08.

### CODE REVIEW

**Comment by abique** [comment]
Actually isn't 24.08 out already?

**Comment by bbhtt** [comment]
> Actually isn't 24.08 out already?

No

> Build [143794 failed](https://buildbot.flathub.org/#/builders/6/builds/143794)

You can create an empty `share` directory (`install -d /app/share`) and the error should be gone. I have added the necessary exceptions. 

Having a metainfo file would be even better then `files/share` will automatically exist.

**Comment by runiq** [comment]
> Having a metainfo file would be even better then `files/share` will automatically exist.

I'll have to read up on what to put in the metainfo of a base extension, but that sounds like a good idea.

**Comment by runiq** [comment]
@hfiguiere I'm trying to create the metainfo file; what license should I use?

**Comment by hfiguiere** [comment]
> Having a metainfo file would be even better then `files/share` will automatically exist.

It was removed by barth in https://github.com/flathub/org.freedesktop.LinuxAudio.BaseExtension/commit/3dde70e4a0062dda6be4f3ba86c285b6eb1e97cd

**Comment by hfiguiere** [comment]
The only reason the base app exists is to have the extension point created before the build start.

**Comment by hfiguiere** [comment]
> @hfiguiere I'm trying to create the metainfo file; what license should I use?

don't.

**Comment by bbhtt** [comment]
You still need to create an empty `/app/share` directory btw, otherwise the build will fail.

**Comment by hfiguiere** [comment]
> You still need to create an empty `/app/share` directory btw, otherwise the build will fail.

This linter should be fixed. This package has `"skip-appstream-check": true`

**Comment by bbhtt** [comment]
We can't know if a directory exists if it's inside the ostree repo until it is checked out, but checking out a non existent directory will error. That comes from ostree.

**Comment by bbhtt** [comment]
The alternative is to checkout the root `/` instead of `/files/share` but that causes issues with large apps over 2 GB.

**Pull request merged**
