### PR TITLE
Improve table readability in README

### PR DESCRIPTION
**Pull request by Marzal**
Format code table

### CODE REVIEW

**Comment by hfiguiere** [comment]
why not instead fixing the file to properly use the markdown table format

**Comment by Marzal** [comment]
> why not instead fixing the file to properly use the markdown table format

I have used markdown a lot in the past, but I wasn't familiar with the table format. Fixed.

**Comment by hfiguiere** [comment]
I didn't realise but the problem is that this is against the deprecated branch, and I don't have permission to set the default branch :-(

**Comment by hfiguiere** [comment]
closed with commit 968dbbe

(merged on the right branch)

**Pull request closed without merging**
